name: Linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  statuses: write

env:
  contents: repos/bewuethr/dotfiles/contents

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    name: Run yamllint
    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.2

      - name: Get yamllint config file from dotfiles
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api "$contents/.config/yamllint/config" \
              --jq '.content | @base64d' \
              | sed '$d' \
              > .yamllint

      - name: Run YAML linter
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .yamllint

  markdownlint:
    runs-on: ubuntu-24.04
    name: Run markdownlint
    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.2

      - name: Get mdl style file from dotfiles
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api "$contents/.config/mdl/style.rb" --jq '.content | @base64d' \
              > .mdl_style.rb

      - name: Run Markdown linter
        uses: ./.
        with:
          style-file: .mdl_style.rb

  shellcheck:
    runs-on: ubuntu-24.04
    name: Run ShellCheck
    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.2

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2

  lint:
    name: Run super-linter job
    uses: bewuethr/workflows/.github/workflows/linter.yml@main
    permissions:
      contents: read
      packages: read
      statuses: write
    with:
      validate-dockerfile: true
